// <auto-generated />
namespace IP_NTier.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users_email_index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_email_index));
        
        string IMigrationMetadata.Id
        {
            get { return "201805010503146_users_email_index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
