// <auto-generated />
namespace IP_NTier.DataAccess.EF.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initial_security_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_security_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201804302354253_initial_security_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
